CREATE TABLE DETAILS(
    ID SERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR(25) NOT NULL ,
    LASTNAME VARCHAR(25) NOT NULL ,
    PHONENUMBER VARCHAR(30) NOT NULL UNIQUE,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    DETAILS_ID INTEGER REFERENCES MEMBERS(ID)
);

CREATE TABLE CAR_DETAILS (
    ID SERIAL PRIMARY KEY,
    MODEL VARCHAR(25) NOT NULL,
    COLOR VARCHAR(25) NOT NULL,
    REGNUMBER VARCHAR(30) NOT NULL UNIQUE,
    YEAROFPUB INTEGER NOT NULL,
    DETAILS_ID INTEGER NOT NULL,
    FOREIGN KEY (DETAILS_ID) REFERENCES MEMBERS(ID)
);

CREATE TABLE CAR_PROBLEM (
    ID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(200) NOT NULL,
    SOLUTION VARCHAR(200) NOT NULL,
    PARTS_PRICE INTEGER NOT NULL,
    HANDWORK_PRICE INTEGER NOT NULL,
    CARDETAILS_ID INTEGER NOT NULL,
    FOREIGN KEY (CARDETAILS_ID) REFERENCES CAR_DETAILS(ID)
);